name: Continuous Deployment to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v10
        with:
          extraPullNames: miso-haskell

      - name: Build site
        run: nix-build

      - name: Publish site
        uses: maxheld83/ghpages@v0.3.0
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: ./result/bin/app.jsexe/

