name: Continuous Deployment to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extraPullNames: miso-haskell

      - name: Build site
        run:
          nix-env -iA cachix -f https://cachix.org/api/v1/install && \
          cachix use miso-haskell &&\
          nix-build

      - name: Publish site
        uses: maxheld83/ghpages@v0.3.0
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: ./result/bin/app.jsexe/

